// Generated by protocol/generate.mjs; edit schema.json.
use super::{Reader, Writer, Wire, Result};
#[derive(Debug, Clone, PartialEq)]
pub struct Handshake {
    pub min_major: u8,
    pub max_major: u8,
    pub minor: u8,
    pub client_id: Vec<u8>,
    pub name: String,
}
impl Wire for Handshake {
    const KIND: u16 = 1;
    fn write(&self, w: &mut Writer) {
        w.u8(self.min_major);
        w.u8(self.max_major);
        w.u8(self.minor);
        w.bytes(&self.client_id);
        w.string(&self.name);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        min_major: r.u8()?,
        max_major: r.u8()?,
        minor: r.u8()?,
        client_id: r.bytes()?,
        name: r.string()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct ProtocolVersion {
    pub major: u8,
    pub minor: u8,
}
impl Wire for ProtocolVersion {
    const KIND: u16 = 2;
    fn write(&self, w: &mut Writer) {
        w.u8(self.major);
        w.u8(self.minor);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        major: r.u8()?,
        minor: r.u8()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct HostInfo {
    pub host_id: Vec<u8>,
    pub name: String,
}
impl Wire for HostInfo {
    const KIND: u16 = 3;
    fn write(&self, w: &mut Writer) {
        w.bytes(&self.host_id);
        w.string(&self.name);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        host_id: r.bytes()?,
        name: r.string()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct ClientInfo {
    pub client_id: Vec<u8>,
    pub name: String,
}
impl Wire for ClientInfo {
    const KIND: u16 = 4;
    fn write(&self, w: &mut Writer) {
        w.bytes(&self.client_id);
        w.string(&self.name);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        client_id: r.bytes()?,
        name: r.string()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct Pairing {
    pub phase: u8,
    pub nonce: Vec<u8>,
    pub proof: Vec<u8>,
    pub secret: Vec<u8>,
}
impl Wire for Pairing {
    const KIND: u16 = 5;
    fn write(&self, w: &mut Writer) {
        w.u8(self.phase);
        w.bytes(&self.nonce);
        w.bytes(&self.proof);
        w.bytes(&self.secret);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        phase: r.u8()?,
        nonce: r.bytes()?,
        proof: r.bytes()?,
        secret: r.bytes()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct SessionStart {
    pub width: u32,
    pub height: u32,
    pub fps: u32,
}
impl Wire for SessionStart {
    const KIND: u16 = 6;
    fn write(&self, w: &mut Writer) {
        w.u32(self.width);
        w.u32(self.height);
        w.u32(self.fps);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        width: r.u32()?,
        height: r.u32()?,
        fps: r.u32()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct SessionStop {
    pub reason: u8,
}
impl Wire for SessionStop {
    const KIND: u16 = 7;
    fn write(&self, w: &mut Writer) {
        w.u8(self.reason);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        reason: r.u8()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct DisplayCapabilities {
    pub physical_width: u32,
    pub physical_height: u32,
    pub logical_width: u32,
    pub logical_height: u32,
    pub max_fps: u32,
    pub native_scale: f32,
    pub safe_top: f32,
    pub safe_right: f32,
    pub safe_bottom: f32,
    pub safe_left: f32,
    pub orientation: u8,
}
impl Wire for DisplayCapabilities {
    const KIND: u16 = 8;
    fn write(&self, w: &mut Writer) {
        w.u32(self.physical_width);
        w.u32(self.physical_height);
        w.u32(self.logical_width);
        w.u32(self.logical_height);
        w.u32(self.max_fps);
        w.f32(self.native_scale);
        w.f32(self.safe_top);
        w.f32(self.safe_right);
        w.f32(self.safe_bottom);
        w.f32(self.safe_left);
        w.u8(self.orientation);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        physical_width: r.u32()?,
        physical_height: r.u32()?,
        logical_width: r.u32()?,
        logical_height: r.u32()?,
        max_fps: r.u32()?,
        native_scale: r.f32()?,
        safe_top: r.f32()?,
        safe_right: r.f32()?,
        safe_bottom: r.f32()?,
        safe_left: r.f32()?,
        orientation: r.u8()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct DisplayMode {
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    pub scale_percent: u32,
}
impl Wire for DisplayMode {
    const KIND: u16 = 9;
    fn write(&self, w: &mut Writer) {
        w.u32(self.width);
        w.u32(self.height);
        w.u32(self.fps);
        w.u32(self.scale_percent);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        width: r.u32()?,
        height: r.u32()?,
        fps: r.u32()?,
        scale_percent: r.u32()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct DisplayModeChange {
    pub width: u32,
    pub height: u32,
    pub fps: u32,
}
impl Wire for DisplayModeChange {
    const KIND: u16 = 10;
    fn write(&self, w: &mut Writer) {
        w.u32(self.width);
        w.u32(self.height);
        w.u32(self.fps);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        width: r.u32()?,
        height: r.u32()?,
        fps: r.u32()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct EncoderCapabilities {
    pub codecs: u32,
    pub hardware: u8,
    pub max_width: u32,
    pub max_height: u32,
}
impl Wire for EncoderCapabilities {
    const KIND: u16 = 11;
    fn write(&self, w: &mut Writer) {
        w.u32(self.codecs);
        w.u8(self.hardware);
        w.u32(self.max_width);
        w.u32(self.max_height);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        codecs: r.u32()?,
        hardware: r.u8()?,
        max_width: r.u32()?,
        max_height: r.u32()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct EncoderConfig {
    pub codec: u8,
    pub bitrate: u32,
    pub fps: u32,
    pub preset: u8,
}
impl Wire for EncoderConfig {
    const KIND: u16 = 12;
    fn write(&self, w: &mut Writer) {
        w.u8(self.codec);
        w.u32(self.bitrate);
        w.u32(self.fps);
        w.u8(self.preset);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        codec: r.u8()?,
        bitrate: r.u32()?,
        fps: r.u32()?,
        preset: r.u8()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct VideoConfig {
    pub generation: u32,
    pub codec: u8,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    pub bit_depth: u8,
    pub color_space: u8,
    pub parameter_sets: Vec<u8>,
}
impl Wire for VideoConfig {
    const KIND: u16 = 13;
    fn write(&self, w: &mut Writer) {
        w.u32(self.generation);
        w.u8(self.codec);
        w.u32(self.width);
        w.u32(self.height);
        w.u32(self.fps);
        w.u8(self.bit_depth);
        w.u8(self.color_space);
        w.bytes(&self.parameter_sets);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        generation: r.u32()?,
        codec: r.u8()?,
        width: r.u32()?,
        height: r.u32()?,
        fps: r.u32()?,
        bit_depth: r.u8()?,
        color_space: r.u8()?,
        parameter_sets: r.bytes()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct VideoFrame {
    pub generation: u32,
    pub frame_id: u64,
    pub capture_timestamp: u64,
    pub encode_timestamp: u64,
    pub send_timestamp: u64,
    pub keyframe: u8,
    pub data: Vec<u8>,
}
impl Wire for VideoFrame {
    const KIND: u16 = 14;
    fn write(&self, w: &mut Writer) {
        w.u32(self.generation);
        w.u64(self.frame_id);
        w.u64(self.capture_timestamp);
        w.u64(self.encode_timestamp);
        w.u64(self.send_timestamp);
        w.u8(self.keyframe);
        w.bytes(&self.data);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        generation: r.u32()?,
        frame_id: r.u64()?,
        capture_timestamp: r.u64()?,
        encode_timestamp: r.u64()?,
        send_timestamp: r.u64()?,
        keyframe: r.u8()?,
        data: r.bytes()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct VideoFragment {
    pub generation: u32,
    pub frame_id: u64,
    pub capture_timestamp: u64,
    pub encode_timestamp: u64,
    pub send_timestamp: u64,
    pub keyframe: u8,
    pub index: u16,
    pub count: u16,
    pub total_bytes: u32,
    pub data: Vec<u8>,
}
impl Wire for VideoFragment {
    const KIND: u16 = 15;
    fn write(&self, w: &mut Writer) {
        w.u32(self.generation);
        w.u64(self.frame_id);
        w.u64(self.capture_timestamp);
        w.u64(self.encode_timestamp);
        w.u64(self.send_timestamp);
        w.u8(self.keyframe);
        w.u16(self.index);
        w.u16(self.count);
        w.u32(self.total_bytes);
        w.bytes(&self.data);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        generation: r.u32()?,
        frame_id: r.u64()?,
        capture_timestamp: r.u64()?,
        encode_timestamp: r.u64()?,
        send_timestamp: r.u64()?,
        keyframe: r.u8()?,
        index: r.u16()?,
        count: r.u16()?,
        total_bytes: r.u32()?,
        data: r.bytes()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct KeyframeRequest {
    pub reason: u8,
}
impl Wire for KeyframeRequest {
    const KIND: u16 = 16;
    fn write(&self, w: &mut Writer) {
        w.u8(self.reason);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        reason: r.u8()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct InputEvent {
    pub kind: u8,
    pub phase: u8,
    pub contact_id: u16,
    pub x: f32,
    pub y: f32,
    pub dx: f32,
    pub dy: f32,
    pub buttons: u32,
    pub physical_key: u16,
    pub logical_key: u32,
    pub modifiers: u16,
    pub is_repeat: u8,
}
impl Wire for InputEvent {
    const KIND: u16 = 17;
    fn write(&self, w: &mut Writer) {
        w.u8(self.kind);
        w.u8(self.phase);
        w.u16(self.contact_id);
        w.f32(self.x);
        w.f32(self.y);
        w.f32(self.dx);
        w.f32(self.dy);
        w.u32(self.buttons);
        w.u16(self.physical_key);
        w.u32(self.logical_key);
        w.u16(self.modifiers);
        w.u8(self.is_repeat);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        kind: r.u8()?,
        phase: r.u8()?,
        contact_id: r.u16()?,
        x: r.f32()?,
        y: r.f32()?,
        dx: r.f32()?,
        dy: r.f32()?,
        buttons: r.u32()?,
        physical_key: r.u16()?,
        logical_key: r.u32()?,
        modifiers: r.u16()?,
        is_repeat: r.u8()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct Ping {
    pub client_timestamp: u64,
}
impl Wire for Ping {
    const KIND: u16 = 18;
    fn write(&self, w: &mut Writer) {
        w.u64(self.client_timestamp);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        client_timestamp: r.u64()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct Pong {
    pub client_timestamp: u64,
    pub host_receive: u64,
    pub host_send: u64,
}
impl Wire for Pong {
    const KIND: u16 = 19;
    fn write(&self, w: &mut Writer) {
        w.u64(self.client_timestamp);
        w.u64(self.host_receive);
        w.u64(self.host_send);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        client_timestamp: r.u64()?,
        host_receive: r.u64()?,
        host_send: r.u64()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct Statistics {
    pub fps: f32,
    pub bitrate: u32,
    pub rtt_us: u32,
    pub loss_ppm: u32,
    pub decode_queue: u16,
    pub dropped_frames: u32,
    pub received_bytes: u64,
    pub decode_us: u32,
    pub render_us: u32,
    pub estimated_latency_us: u32,
}
impl Wire for Statistics {
    const KIND: u16 = 20;
    fn write(&self, w: &mut Writer) {
        w.f32(self.fps);
        w.u32(self.bitrate);
        w.u32(self.rtt_us);
        w.u32(self.loss_ppm);
        w.u16(self.decode_queue);
        w.u32(self.dropped_frames);
        w.u64(self.received_bytes);
        w.u32(self.decode_us);
        w.u32(self.render_us);
        w.u32(self.estimated_latency_us);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        fps: r.f32()?,
        bitrate: r.u32()?,
        rtt_us: r.u32()?,
        loss_ppm: r.u32()?,
        decode_queue: r.u16()?,
        dropped_frames: r.u32()?,
        received_bytes: r.u64()?,
        decode_us: r.u32()?,
        render_us: r.u32()?,
        estimated_latency_us: r.u32()?,
    }) }
}
#[derive(Debug, Clone, PartialEq)]
pub struct ProtocolError {
    pub code: u16,
    pub message: String,
}
impl Wire for ProtocolError {
    const KIND: u16 = 21;
    fn write(&self, w: &mut Writer) {
        w.u16(self.code);
        w.string(&self.message);
    }
    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {
        code: r.u16()?,
        message: r.string()?,
    }) }
}
