// The checked-in Rust and Swift wire types are generated from this single schema.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const schema = JSON.parse(fs.readFileSync(path.join(root, 'protocol/schema.json')));
const rustTypes = {u8:'u8',u16:'u16',u32:'u32',u64:'u64',i32:'i32',f32:'f32',string:'String',bytes:'Vec<u8>'};
const swiftTypes = {u8:'UInt8',u16:'UInt16',u32:'UInt32',u64:'UInt64',i32:'Int32',f32:'Float',string:'String',bytes:'Data'};
const camel = s => s.replace(/_([a-z])/g,(_, c)=>c.toUpperCase());
let rs = '// Generated by protocol/generate.mjs; edit schema.json.\nuse super::{Reader, Writer, Wire, Result};\n';
let sw = '// Generated by protocol/generate.mjs; edit schema.json.\nimport Foundation\n';
for (const m of schema.messages) {
  rs += `#[derive(Debug, Clone, PartialEq)]\npub struct ${m.name} {\n`;
  sw += `struct ${m.name}: Sendable {\n`;
  for (const [n,t] of m.fields) { rs += `    pub ${n}: ${rustTypes[t]},\n`; sw += `    var ${camel(n)}: ${swiftTypes[t]}\n`; }
  rs += `}\nimpl Wire for ${m.name} {\n    const KIND: u16 = ${m.id};\n    fn write(&self, w: &mut Writer) {\n`;
  sw += `}\nextension ${m.name}: WireMessage {\n    static let kind: UInt16 = ${m.id}\n    func write(to w: inout WireWriter) {\n`;
  for (const [n,t] of m.fields) { rs += `        w.${t}(${t==='bytes' || t==='string' ? '&' : ''}self.${n});\n`; sw += `        w.${t}(self.${camel(n)})\n`; }
  rs += `    }\n    fn read(r: &mut Reader<'_>) -> Result<Self> { Ok(Self {\n`;
  sw += `    }\n    init(from r: inout WireReader) throws {\n`;
  for (const [n,t] of m.fields) { rs += `        ${n}: r.${t}()?,\n`; sw += `        ${camel(n)} = try r.${t}()\n`; }
  rs += `    }) }\n}\n`; sw += `    }\n}\n`;
}
for (const [dest, content] of [['windows/host/src/protocol/generated.rs',rs],['ipad/SidecarDOS/Protocol/Generated.swift',sw]]) {
  const p = path.join(root,dest);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(p) || fs.readFileSync(p,'utf8') !== content) throw new Error(`${dest} is stale`);
  } else { fs.mkdirSync(path.dirname(p),{recursive:true}); fs.writeFileSync(p,content); }
}
