// Generated by protocol/generate.mjs; edit schema.json.
import Foundation
struct Handshake: Sendable {
    var minMajor: UInt8
    var maxMajor: UInt8
    var minor: UInt8
    var clientId: Data
    var name: String
    var trusted: UInt8
}
extension Handshake: WireMessage {
    static let kind: UInt16 = 1
    func write(to w: inout WireWriter) {
        w.u8(self.minMajor)
        w.u8(self.maxMajor)
        w.u8(self.minor)
        w.bytes(self.clientId)
        w.string(self.name)
        w.u8(self.trusted)
    }
    init(from r: inout WireReader) throws {
        minMajor = try r.u8()
        maxMajor = try r.u8()
        minor = try r.u8()
        clientId = try r.bytes()
        name = try r.string()
        trusted = try r.u8()
    }
}
struct ProtocolVersion: Sendable {
    var major: UInt8
    var minor: UInt8
}
extension ProtocolVersion: WireMessage {
    static let kind: UInt16 = 2
    func write(to w: inout WireWriter) {
        w.u8(self.major)
        w.u8(self.minor)
    }
    init(from r: inout WireReader) throws {
        major = try r.u8()
        minor = try r.u8()
    }
}
struct HostInfo: Sendable {
    var hostId: Data
    var name: String
}
extension HostInfo: WireMessage {
    static let kind: UInt16 = 3
    func write(to w: inout WireWriter) {
        w.bytes(self.hostId)
        w.string(self.name)
    }
    init(from r: inout WireReader) throws {
        hostId = try r.bytes()
        name = try r.string()
    }
}
struct ClientInfo: Sendable {
    var clientId: Data
    var name: String
}
extension ClientInfo: WireMessage {
    static let kind: UInt16 = 4
    func write(to w: inout WireWriter) {
        w.bytes(self.clientId)
        w.string(self.name)
    }
    init(from r: inout WireReader) throws {
        clientId = try r.bytes()
        name = try r.string()
    }
}
struct Pairing: Sendable {
    var phase: UInt8
    var nonce: Data
    var proof: Data
    var secret: Data
}
extension Pairing: WireMessage {
    static let kind: UInt16 = 5
    func write(to w: inout WireWriter) {
        w.u8(self.phase)
        w.bytes(self.nonce)
        w.bytes(self.proof)
        w.bytes(self.secret)
    }
    init(from r: inout WireReader) throws {
        phase = try r.u8()
        nonce = try r.bytes()
        proof = try r.bytes()
        secret = try r.bytes()
    }
}
struct SessionStart: Sendable {
    var width: UInt32
    var height: UInt32
    var fps: UInt32
}
extension SessionStart: WireMessage {
    static let kind: UInt16 = 6
    func write(to w: inout WireWriter) {
        w.u32(self.width)
        w.u32(self.height)
        w.u32(self.fps)
    }
    init(from r: inout WireReader) throws {
        width = try r.u32()
        height = try r.u32()
        fps = try r.u32()
    }
}
struct SessionStop: Sendable {
    var reason: UInt8
}
extension SessionStop: WireMessage {
    static let kind: UInt16 = 7
    func write(to w: inout WireWriter) {
        w.u8(self.reason)
    }
    init(from r: inout WireReader) throws {
        reason = try r.u8()
    }
}
struct DisplayCapabilities: Sendable {
    var physicalWidth: UInt32
    var physicalHeight: UInt32
    var logicalWidth: UInt32
    var logicalHeight: UInt32
    var maxFps: UInt32
    var nativeScale: Float
    var safeTop: Float
    var safeRight: Float
    var safeBottom: Float
    var safeLeft: Float
    var orientation: UInt8
}
extension DisplayCapabilities: WireMessage {
    static let kind: UInt16 = 8
    func write(to w: inout WireWriter) {
        w.u32(self.physicalWidth)
        w.u32(self.physicalHeight)
        w.u32(self.logicalWidth)
        w.u32(self.logicalHeight)
        w.u32(self.maxFps)
        w.f32(self.nativeScale)
        w.f32(self.safeTop)
        w.f32(self.safeRight)
        w.f32(self.safeBottom)
        w.f32(self.safeLeft)
        w.u8(self.orientation)
    }
    init(from r: inout WireReader) throws {
        physicalWidth = try r.u32()
        physicalHeight = try r.u32()
        logicalWidth = try r.u32()
        logicalHeight = try r.u32()
        maxFps = try r.u32()
        nativeScale = try r.f32()
        safeTop = try r.f32()
        safeRight = try r.f32()
        safeBottom = try r.f32()
        safeLeft = try r.f32()
        orientation = try r.u8()
    }
}
struct DisplayMode: Sendable {
    var width: UInt32
    var height: UInt32
    var fps: UInt32
    var scalePercent: UInt32
}
extension DisplayMode: WireMessage {
    static let kind: UInt16 = 9
    func write(to w: inout WireWriter) {
        w.u32(self.width)
        w.u32(self.height)
        w.u32(self.fps)
        w.u32(self.scalePercent)
    }
    init(from r: inout WireReader) throws {
        width = try r.u32()
        height = try r.u32()
        fps = try r.u32()
        scalePercent = try r.u32()
    }
}
struct DisplayModeChange: Sendable {
    var width: UInt32
    var height: UInt32
    var fps: UInt32
}
extension DisplayModeChange: WireMessage {
    static let kind: UInt16 = 10
    func write(to w: inout WireWriter) {
        w.u32(self.width)
        w.u32(self.height)
        w.u32(self.fps)
    }
    init(from r: inout WireReader) throws {
        width = try r.u32()
        height = try r.u32()
        fps = try r.u32()
    }
}
struct EncoderCapabilities: Sendable {
    var codecs: UInt32
    var hardware: UInt8
    var maxWidth: UInt32
    var maxHeight: UInt32
}
extension EncoderCapabilities: WireMessage {
    static let kind: UInt16 = 11
    func write(to w: inout WireWriter) {
        w.u32(self.codecs)
        w.u8(self.hardware)
        w.u32(self.maxWidth)
        w.u32(self.maxHeight)
    }
    init(from r: inout WireReader) throws {
        codecs = try r.u32()
        hardware = try r.u8()
        maxWidth = try r.u32()
        maxHeight = try r.u32()
    }
}
struct EncoderConfig: Sendable {
    var codec: UInt8
    var bitrate: UInt32
    var fps: UInt32
    var preset: UInt8
}
extension EncoderConfig: WireMessage {
    static let kind: UInt16 = 12
    func write(to w: inout WireWriter) {
        w.u8(self.codec)
        w.u32(self.bitrate)
        w.u32(self.fps)
        w.u8(self.preset)
    }
    init(from r: inout WireReader) throws {
        codec = try r.u8()
        bitrate = try r.u32()
        fps = try r.u32()
        preset = try r.u8()
    }
}
struct VideoConfig: Sendable {
    var generation: UInt32
    var codec: UInt8
    var width: UInt32
    var height: UInt32
    var fps: UInt32
    var bitDepth: UInt8
    var colorSpace: UInt8
    var parameterSets: Data
}
extension VideoConfig: WireMessage {
    static let kind: UInt16 = 13
    func write(to w: inout WireWriter) {
        w.u32(self.generation)
        w.u8(self.codec)
        w.u32(self.width)
        w.u32(self.height)
        w.u32(self.fps)
        w.u8(self.bitDepth)
        w.u8(self.colorSpace)
        w.bytes(self.parameterSets)
    }
    init(from r: inout WireReader) throws {
        generation = try r.u32()
        codec = try r.u8()
        width = try r.u32()
        height = try r.u32()
        fps = try r.u32()
        bitDepth = try r.u8()
        colorSpace = try r.u8()
        parameterSets = try r.bytes()
    }
}
struct VideoFrame: Sendable {
    var generation: UInt32
    var frameId: UInt64
    var captureTimestamp: UInt64
    var encodeTimestamp: UInt64
    var sendTimestamp: UInt64
    var keyframe: UInt8
    var data: Data
}
extension VideoFrame: WireMessage {
    static let kind: UInt16 = 14
    func write(to w: inout WireWriter) {
        w.u32(self.generation)
        w.u64(self.frameId)
        w.u64(self.captureTimestamp)
        w.u64(self.encodeTimestamp)
        w.u64(self.sendTimestamp)
        w.u8(self.keyframe)
        w.bytes(self.data)
    }
    init(from r: inout WireReader) throws {
        generation = try r.u32()
        frameId = try r.u64()
        captureTimestamp = try r.u64()
        encodeTimestamp = try r.u64()
        sendTimestamp = try r.u64()
        keyframe = try r.u8()
        data = try r.bytes()
    }
}
struct VideoFragment: Sendable {
    var generation: UInt32
    var frameId: UInt64
    var captureTimestamp: UInt64
    var encodeTimestamp: UInt64
    var sendTimestamp: UInt64
    var keyframe: UInt8
    var index: UInt16
    var count: UInt16
    var totalBytes: UInt32
    var data: Data
}
extension VideoFragment: WireMessage {
    static let kind: UInt16 = 15
    func write(to w: inout WireWriter) {
        w.u32(self.generation)
        w.u64(self.frameId)
        w.u64(self.captureTimestamp)
        w.u64(self.encodeTimestamp)
        w.u64(self.sendTimestamp)
        w.u8(self.keyframe)
        w.u16(self.index)
        w.u16(self.count)
        w.u32(self.totalBytes)
        w.bytes(self.data)
    }
    init(from r: inout WireReader) throws {
        generation = try r.u32()
        frameId = try r.u64()
        captureTimestamp = try r.u64()
        encodeTimestamp = try r.u64()
        sendTimestamp = try r.u64()
        keyframe = try r.u8()
        index = try r.u16()
        count = try r.u16()
        totalBytes = try r.u32()
        data = try r.bytes()
    }
}
struct KeyframeRequest: Sendable {
    var reason: UInt8
}
extension KeyframeRequest: WireMessage {
    static let kind: UInt16 = 16
    func write(to w: inout WireWriter) {
        w.u8(self.reason)
    }
    init(from r: inout WireReader) throws {
        reason = try r.u8()
    }
}
struct InputEvent: Sendable {
    var kind: UInt8
    var phase: UInt8
    var contactId: UInt16
    var x: Float
    var y: Float
    var dx: Float
    var dy: Float
    var buttons: UInt32
    var physicalKey: UInt16
    var logicalKey: UInt32
    var modifiers: UInt16
    var isRepeat: UInt8
}
extension InputEvent: WireMessage {
    static let kind: UInt16 = 17
    func write(to w: inout WireWriter) {
        w.u8(self.kind)
        w.u8(self.phase)
        w.u16(self.contactId)
        w.f32(self.x)
        w.f32(self.y)
        w.f32(self.dx)
        w.f32(self.dy)
        w.u32(self.buttons)
        w.u16(self.physicalKey)
        w.u32(self.logicalKey)
        w.u16(self.modifiers)
        w.u8(self.isRepeat)
    }
    init(from r: inout WireReader) throws {
        kind = try r.u8()
        phase = try r.u8()
        contactId = try r.u16()
        x = try r.f32()
        y = try r.f32()
        dx = try r.f32()
        dy = try r.f32()
        buttons = try r.u32()
        physicalKey = try r.u16()
        logicalKey = try r.u32()
        modifiers = try r.u16()
        isRepeat = try r.u8()
    }
}
struct Ping: Sendable {
    var clientTimestamp: UInt64
}
extension Ping: WireMessage {
    static let kind: UInt16 = 18
    func write(to w: inout WireWriter) {
        w.u64(self.clientTimestamp)
    }
    init(from r: inout WireReader) throws {
        clientTimestamp = try r.u64()
    }
}
struct Pong: Sendable {
    var clientTimestamp: UInt64
    var hostReceive: UInt64
    var hostSend: UInt64
}
extension Pong: WireMessage {
    static let kind: UInt16 = 19
    func write(to w: inout WireWriter) {
        w.u64(self.clientTimestamp)
        w.u64(self.hostReceive)
        w.u64(self.hostSend)
    }
    init(from r: inout WireReader) throws {
        clientTimestamp = try r.u64()
        hostReceive = try r.u64()
        hostSend = try r.u64()
    }
}
struct Statistics: Sendable {
    var fps: Float
    var bitrate: UInt32
    var rttUs: UInt32
    var lossPpm: UInt32
    var decodeQueue: UInt16
    var droppedFrames: UInt32
    var receivedBytes: UInt64
    var decodeUs: UInt32
    var renderUs: UInt32
    var estimatedLatencyUs: UInt32
}
extension Statistics: WireMessage {
    static let kind: UInt16 = 20
    func write(to w: inout WireWriter) {
        w.f32(self.fps)
        w.u32(self.bitrate)
        w.u32(self.rttUs)
        w.u32(self.lossPpm)
        w.u16(self.decodeQueue)
        w.u32(self.droppedFrames)
        w.u64(self.receivedBytes)
        w.u32(self.decodeUs)
        w.u32(self.renderUs)
        w.u32(self.estimatedLatencyUs)
    }
    init(from r: inout WireReader) throws {
        fps = try r.f32()
        bitrate = try r.u32()
        rttUs = try r.u32()
        lossPpm = try r.u32()
        decodeQueue = try r.u16()
        droppedFrames = try r.u32()
        receivedBytes = try r.u64()
        decodeUs = try r.u32()
        renderUs = try r.u32()
        estimatedLatencyUs = try r.u32()
    }
}
struct ProtocolError: Sendable {
    var code: UInt16
    var message: String
}
extension ProtocolError: WireMessage {
    static let kind: UInt16 = 21
    func write(to w: inout WireWriter) {
        w.u16(self.code)
        w.string(self.message)
    }
    init(from r: inout WireReader) throws {
        code = try r.u16()
        message = try r.string()
    }
}
